language: cpp

sudo: true

os:
  - linux

compiler:
  - g++
  - clang

before_script:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install libibus-1.0-dev qt5-default qtdeclarative5-dev
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX='/usr'

script:
  - make
