language: cpp
os:
  - linux
sudo: required
dist: trusty
compiler:
  - g++
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt591-trusty
  - sudo apt-get update -qq
  - sudo apt-get install libibus-1.0-dev qt59base qt59declarative
  - source /opt/qt59/bin/qt59-env.sh
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
