language: cpp
os:
  - linux
sudo: required
dist: trusty
compiler:
  - g++
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq
  - sudo apt-get install libibus-1.0-dev qt55base
  - source /opt/qt55/bin/qt55-env.sh
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
